// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiS8Z7uGejhfcBRar-JJjCy74djufEfTY',
    appId: '1:313630731376:web:240dc6e3f2c01ea64818b5',
    messagingSenderId: '313630731376',
    projectId: 'attendance-app-cae1a',
    authDomain: 'attendance-app-cae1a.firebaseapp.com',
    storageBucket: 'attendance-app-cae1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jSpnfq0NqfrrKMvUIm1O9HLaTHKBpp4',
    appId: '1:313630731376:android:13cd273024db250a4818b5',
    messagingSenderId: '313630731376',
    projectId: 'attendance-app-cae1a',
    storageBucket: 'attendance-app-cae1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNsf6B3rLB6gm7UBEWHWBW45P_revvaC4',
    appId: '1:313630731376:ios:9ecf7b009ac483504818b5',
    messagingSenderId: '313630731376',
    projectId: 'attendance-app-cae1a',
    storageBucket: 'attendance-app-cae1a.appspot.com',
    iosBundleId: 'com.dizayn3r.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNsf6B3rLB6gm7UBEWHWBW45P_revvaC4',
    appId: '1:313630731376:ios:d04c28f74fd2ee604818b5',
    messagingSenderId: '313630731376',
    projectId: 'attendance-app-cae1a',
    storageBucket: 'attendance-app-cae1a.appspot.com',
    iosBundleId: 'com.dizayn3r.attendanceApp.RunnerTests',
  );
}
